# Houses Prices - Modeling and model selection

## Objective

This notebook develops the first modeling stage of the Houses Prices Project.

The goals are:

1.  Establish baseline performance.
2.  Compare multiple regression models.
3.  Select the most promising model using cross-validation.
4.  Improve the selected model through hyperparameter tuning.
5.  Evaluate the final model on the test set.
6.  Interpret results and identify possible failure modes.

## Methodological Principles

This notebook follows a professional machine learning workflow:

* The preprocessing pipeline is reused from the data processing notebook.
*   The test set is kept untouched until the final evaluation.
*   Baseline models are established before tuning.
*   Model selection is based on quantitative metrics.
*   Final conclusions must justify why a model is chosen.

# Models to Evaluate
## Baseline models

* Dummy Regressor
* Linear Regression
* Decision Tree Regression

## Candidate models

*  Random Forest Regression
*  Ridge Regression
*  Lasso Regression
*  Elastic Net Regression
* Support Vector Regression
* HistGradientBoostingRegressor

Main Evaluation Metrics

The main metric for model selection will be Root Mean Squared Error (RMSE).

Additional metrics:

*    Mean Absolute Error (MAE)
 *   Mean Squared Error (MSE)
 *   R2 – Score
 *   Huber Loss

General Structure of a Scikit Learn Model

from sklearn.modelo import Modelo

1. Instanciar (definir hiperparámetros)
model = Modelo(param1=..., param2=...)

2. Entrenar
model.fit(X_train, y_train)

3. Predecir
y_pred = model.predict(X_test)

(Opcional)

probs = model.predict_proba(X_test)

# Main Imports and Configurations

In [1]:
from pathlib import Path
import warnings

import joblib
import numpy as np
import pandas as pd

from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor

from sklearn.metrics import (
    root_mean_squared_error,
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    make_scorer,
)
def huber_loss(y_true, y_pred, delta=1.0):
    error = y_true - y_pred
    is_small_error = np.abs(error) <= delta
    squared_loss = 0.5 * error**2
    linear_loss = delta * (np.abs(error) - 0.5 * delta)
    return np.mean(np.where(is_small_error, squared_loss, linear_loss))
huber_scorer = make_scorer(huber_loss, greater_is_better=False, delta=1.0)
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor

warnings.filterwarnings("ignore")

RANDOM_STATE = 42
N_SPLITS = 5

CV = StratifiedKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE,
)

SCORING = {
    "neg_root_mean_squared_error": "neg_root_mean_squared_error",
    "neg_mean_absolute_error": "neg_mean_absolute_error",
    "neg_mean_squared_error": "neg_mean_squared_error",
    "r2": "r2",
    "huber_loss": huber_scorer,
}

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 120)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Setup and Experiment Configuration

This cell imports the models, metrics, and utilities required for the modeling phase.

It also defines:

* a fixed random seed for reproducibility,
 *   the cross-validation strategy,
  *  and the evaluation metrics used throughout the notebook.

Cross-validation is configured with stratified folds in order to preserve the class distribution across splits.

In [3]:
X_train, X_test, y_train, y_test = joblib.load('/content/drive/MyDrive/Split_Data.joblib')

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)
print("Train target mean:", y_train.mean())
print("Test target mean:", y_test.mean())

Train shape: (1168, 29)
Test shape: (292, 29)
Train target mean: 11.50513698630137
Test target mean: 11.506849315068493

# Full Modeling Pipeline

This helper function creates a complete sklearn pipeline by combining:

1.  the preprocessing steps defined in Notebook 2,
2.  the regressor to be trained.

This is a critical design choice because it ensures that:

*   preprocessing is applied consistently,
*  transformations are learned only from training data,
*   and data leakage is avoided during cross-validation and testing.

In [4]:
baseline_models = {
    "dummy": DummyRegressor(strategy="mean"),
    "linear_regression": LinearRegression(
        positive=True,
    ),
    "decision_tree": DecisionTreeRegressor(
        random_state=RANDOM_STATE,
    ),
}

candidate_models = {
    "random_forest": RandomForestRegressor(
        n_estimators=320,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    ),
    "ridge": Ridge(
    ),
    "lasso": Lasso(
    ),
    "elastic_net": ElasticNet(
    ),
    "support_vector": SVR(
    ),
    "hist_gradient_boosting": HistGradientBoostingRegressor(
        random_state=RANDOM_STATE,
    ),
}

# Initial Model Set

This notebook evaluates two groups of models:

## Baseline models

* Dummy Regressor
* Multiple Linear Regression
* Decision Tree Regression

## Candidate models

*  Random Forest Regression
*  Ridge Regression
*  Lasso Regression
*  Elastic Net Regression
* Support Vector Regression
* HistGradientBoostingRegressor

The goal is not to try every possible algorithm, but to compare a small set of relevant models in a structured way.

In [5]:
def evaluate_model_cv(model_name, model, X_train, y_train):
    """
    Evaluate a classification model using stratified cross-validation.

    Parameters
    ----------
    model_name : str
        Name used to identify the model in the output table.
    model : sklearn estimator
        Classification model to evaluate.
    X_train : pandas.DataFrame
        Training feature matrix.
    y_train : pandas.Series
        Training target vector.

    Returns
    -------
    dict
        Dictionary containing the model name and mean cross-validation metrics.
    """
    model_pipeline = model

    cv_results = cross_validate(
        estimator=model_pipeline,
        X=X_train,
        y=y_train,
        cv=CV,
        scoring=SCORING,
        n_jobs=-1,
        return_train_score=False,
    )

    return {
        "model": model_name,
        "cv_RMSE_mean": np.mean(cv_results["test_neg_root_mean_squared_error"]),
        "cv_MAE_mean": np.mean(cv_results["test_neg_mean_absolute_error"]),
        "cv_MSE_mean": np.mean(cv_results["test_neg_mean_squared_error"]),
        "cv_r2_mean": np.mean(cv_results["test_r2"]),
        "cv_huber_loss_mean": np.mean(cv_results["test_huber_loss"]),
    }

Cross-Validation Evaluation Function

This function evaluates a model using stratified cross-validation.

For each model, it:

1.  builds a full pipeline with regressor,
2.  performs cross-validation on the training set,
3.   computes the mean values of the selected evaluation metrics.

This design allows us to compare models under the same conditions before making any tuning or final selection decisions.

In [6]:
baseline_results = []

for model_name, model in baseline_models.items():
    result = evaluate_model_cv(
        model_name=model_name,
        model=model,
        X_train=X_train,
        y_train=y_train,
    )
    baseline_results.append(result)

baseline_results_df = (
    pd.DataFrame(baseline_results)
    .sort_values(by="cv_RMSE_mean", ascending=False)
    .reset_index(drop=True)
)

baseline_results_df

               model  cv_RMSE_mean  cv_MAE_mean  cv_MSE_mean  cv_r2_mean  cv_huber_loss_mean
0  linear_regression     -0.308941    -0.243035    -0.095748    0.664825           -0.047293
1      decision_tree     -0.391783    -0.152412    -0.154129    0.460230           -0.076635
2              dummy     -0.534727    -0.517955    -0.285943   -0.000126           -0.140728

# Baseline Model Results

This table summarizes the performance of the baseline models.

The purpose of this stage is to establish a minimum reference point. In particular, the Dummy Regressor tells us how well a trivial strategy performs, while Linear Regression and Decision Tree provide stronger but still simple baselines.

Any candidate model should clearly outperform these results

In [7]:
candidate_results = []

for model_name, model in candidate_models.items():
    result = evaluate_model_cv(
        model_name=model_name,
        model=model,
        X_train=X_train,
        y_train=y_train,
    )
    candidate_results.append(result)

candidate_results_df = (
    pd.DataFrame(candidate_results)
    .sort_values(by="cv_RMSE_mean", ascending=False)
    .reset_index(drop=True)
)

candidate_results_df

                    model  cv_RMSE_mean  cv_MAE_mean  cv_MSE_mean  cv_r2_mean  cv_huber_loss_mean
0           random_forest     -0.279589    -0.149520    -0.078650    0.724652           -0.039039
1  hist_gradient_boosting     -0.293833    -0.173533    -0.086798    0.696113           -0.043078
2                   ridge     -0.309869    -0.242245    -0.096299    0.662823           -0.047631
3             elastic_net     -0.373435    -0.294109    -0.139736    0.510753           -0.069161
4                   lasso     -0.376444    -0.301461    -0.141971    0.502962           -0.070288
5          support_vector     -0.394451    -0.327844    -0.155885    0.454254           -0.077486

# Candidate Model Results

This table summarizes the performance of the stronger candidate models.
A good amount of these as it stands are as good or worse compared to linear regression, further adjustments of parameters is neccesary.

These models are expected to capture more complex relationships than the baselines. However, they also introduce a greater risk of overfitting, so their performance must be interpreted carefully.

In [8]:
all_results_df = (
    pd.concat([baseline_results_df, candidate_results_df], ignore_index=True)
    .sort_values(by="cv_RMSE_mean", ascending=False)
    .reset_index(drop=True)
)

all_results_df

                    model  cv_RMSE_mean  cv_MAE_mean  cv_MSE_mean  cv_r2_mean  cv_huber_loss_mean
0           random_forest     -0.279589    -0.149520    -0.078650    0.724652           -0.039039
1  hist_gradient_boosting     -0.293833    -0.173533    -0.086798    0.696113           -0.043078
2       linear_regression     -0.308941    -0.243035    -0.095748    0.664825           -0.047293
3                   ridge     -0.309869    -0.242245    -0.096299    0.662823           -0.047631
4             elastic_net     -0.373435    -0.294109    -0.139736    0.510753           -0.069161
5                   lasso     -0.376444    -0.301461    -0.141971    0.502962           -0.070288
6           decision_tree     -0.391783    -0.152412    -0.154129    0.460230           -0.076635
7          support_vector     -0.394451    -0.327844    -0.155885    0.454254           -0.077486
8                   dummy     -0.534727    -0.517955    -0.285943   -0.000126           -0.140728

Model Comparison Summary

This consolidated table compares all evaluated models using the same cross-validation setup.

The main criterion for model selection is root mean squared error, while mean absolute error, mean squared error, r2 score and huber loss are used as complementary metrics.

The next step is to select the most promising model or models for hyperparameter tuning.

In [9]:
best_model_name = all_results_df.iloc[0]["model"]
best_model_name

'random_forest'

# Preliminary Best Model Selection

This cell identifies the model with the lowest mean squared error.

This is only a preliminary selection. The final decision will be made after hyperparameter tuning and evaluation on the untouched test set.

# Hyperparameter tuning step

At this stage, we optimize the strongest candidate models using Optuna.

The objective is to improve performance by searching for better hyperparameter configurations while keeping the evaluation rigorous.

Important principles:

  *  Tuning is performed only on the training set.
  *  Cross-validation is used inside the optimization process.
  *  The test set remains untouched until the final evaluation.

In [10]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 7.5 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [11]:
import optuna

In [12]:
def objective_elastic_net(trial):
    # Define hyperparameters to tune
    model = ElasticNet(
        alpha=trial.suggest_float("alpha", 1e-5, 10.0, log=True),
        l1_ratio=trial.suggest_float("l1_ratio", 0.0, 1.0),
    )

    model_pipeline = model

    cv_results = cross_validate(
        estimator=model_pipeline,
        X=X_train,
        y=y_train,
        cv=CV,
        scoring={"neg_root_mean_squared_error": "neg_root_mean_squared_error"},
        n_jobs=-1,
        return_train_score=False,
    )

    return -np.mean(cv_results["test_neg_root_mean_squared_error"])

# Elastic Net Objective Function

This function defines the search space for Elastic Net and tells Optuna how to evaluate each trial.

For every sampled configuration:

1.    a Elastic Net model is created,
2.  it is wrapped into the full preprocessing pipeline,
3.  cross-validation is performed on the training data,
4.  the RMSE is returned.

This ensures that tuning is based on the same metric used for model comparison.

In [13]:
study_elastic_net = optuna.create_study(direction="minimize")
study_elastic_net.optimize(objective_elastic_net, n_trials=50)

[I 2026-04-15 06:28:31,806] A new study created in memory with name: no-name-77c397b3-d405-4c76-9978-a4bcae832e2a
[I 2026-04-15 06:28:32,133] Trial 0 finished with value: 0.3159041688972149 and parameters: {'alpha': 0.016693583993216906, 'l1_ratio': 0.8345354769856409}. Best is trial 0 with value: 0.3159041688972149.
[I 2026-04-15 06:28:32,498] Trial 1 finished with value: 0.3819121375529124 and parameters: {'alpha': 1.9242815036206953, 'l1_ratio': 0.8017537014625302}. Best is trial 0 with value: 0.3159041688972149.
[I 2026-04-15 06:28:32,816] Trial 2 finished with value: 0.31290887391205835 and parameters: {'alpha': 0.011006357963819572, 'l1_ratio': 0.7018571244023959}. Best is trial 2 with value: 0.31290887391205835.
[I 2026-04-15 06:28:32,966] Trial 3 finished with value: 0.3227784115684782 and parameters: {'alpha': 0.0569541196680574, 'l1_ratio': 0.781049737338206}. Best is trial 2 with value: 0.31290887391205835.
[I 2026-04-15 06:28:33,133] Trial 4 finished with value: 0.31001306429038616 and parameters: {'alpha': 0.00022423215836500553, 'l1_ratio': 0.5605569061970822}. Best is trial 4 with value: 0.31001306429038616.
[I 2026-04-15 06:28:33,284] Trial 5 finished with value: 0.3107647701671477 and parameters: {'alpha': 0.006076500130141176, 'l1_ratio': 0.517697423473607}. Best is trial 4 with value: 0.31001306429038616.
[I 2026-04-15 06:28:33,453] Trial 6 finished with value: 0.31059009070696336 and parameters: {'alpha': 2.8662849321163018e-05, 'l1_ratio': 0.9046260509076067}. Best is trial 4 with value: 0.31001306429038616.
[I 2026-04-15 06:28:33,587] Trial 7 finished with value: 0.31053740196561386 and parameters: {'alpha': 3.886177756327438e-05, 'l1_ratio': 0.979850519131646}. Best is trial 4 with value: 0.31001306429038616.
[I 2026-04-15 06:28:33,674] Trial 8 finished with value: 0.316966821302223 and parameters: {'alpha': 0.20598449018042583, 'l1_ratio': 0.067532880555502}. Best is trial 4 with value: 0.31001306429038616.
[I 2026-04-15 06:28:33,862] Trial 9 finished with value: 0.3105508352009134 and parameters: {'alpha': 7.425418636724509e-05, 'l1_ratio': 0.14379011838434796}. Best is trial 4 with value: 0.31001306429038616.
[I 2026-04-15 06:28:34,052] Trial 10 finished with value: 0.3094472999222108 and parameters: {'alpha': 0.0006853781423330098, 'l1_ratio': 0.3453013093765505}. Best is trial 10 with value: 0.3094472999222108.
[I 2026-04-15 06:28:34,249] Trial 11 finished with value: 0.30942356044109404 and parameters: {'alpha': 0.0007337791691638529, 'l1_ratio': 0.32985325442151203}. Best is trial 11 with value: 0.30942356044109404.
[I 2026-04-15 06:28:34,450] Trial 12 finished with value: 0.309327402831863 and parameters: {'alpha': 0.0010645716385642256, 'l1_ratio': 0.276458953185016}. Best is trial 12 with value: 0.309327402831863.
[I 2026-04-15 06:28:34,714] Trial 13 finished with value: 0.3093630796847107 and parameters: {'alpha': 0.0009093077251230667, 'l1_ratio': 0.287564914021347}. Best is trial 12 with value: 0.309327402831863.
[I 2026-04-15 06:28:34,935] Trial 14 finished with value: 0.3093131759772674 and parameters: {'alpha': 0.0020012235902467012, 'l1_ratio': 0.264394344668304}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:35,203] Trial 15 finished with value: 0.3094622420239842 and parameters: {'alpha': 0.0018142602790112749, 'l1_ratio': 0.17052814476031725}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:35,371] Trial 16 finished with value: 0.34597020493952596 and parameters: {'alpha': 0.34418106543864657, 'l1_ratio': 0.41304928981359934}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:35,570] Trial 17 finished with value: 0.31041903996728265 and parameters: {'alpha': 0.0001785779292286265, 'l1_ratio': 0.0037798280837239018}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:35,701] Trial 18 finished with value: 0.30939332480460013 and parameters: {'alpha': 0.003603006247209839, 'l1_ratio': 0.20888165275926987}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:35,926] Trial 19 finished with value: 0.32035578968351547 and parameters: {'alpha': 0.0471809005387514, 'l1_ratio': 0.6397223135812118}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:36,110] Trial 20 finished with value: 0.403985168677422 and parameters: {'alpha': 8.00233797048689, 'l1_ratio': 0.4043472220913634}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:36,406] Trial 21 finished with value: 0.30938013140182336 and parameters: {'alpha': 0.000971640860622088, 'l1_ratio': 0.2539794508955465}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:36,724] Trial 22 finished with value: 0.30999786169277527 and parameters: {'alpha': 0.00032251429717108595, 'l1_ratio': 0.2842968808454191}. Best is trial 14 with value: 0.3093131759772674.
[I 2026-04-15 06:28:36,942] Trial 23 finished with value: 0.3092004774177247 and parameters: {'alpha': 0.002583820012501404, 'l1_ratio': 0.4262743407384234}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,083] Trial 24 finished with value: 0.3092860272866292 and parameters: {'alpha': 0.0033460641562961706, 'l1_ratio': 0.4565563823768599}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,196] Trial 25 finished with value: 0.31468124125789 and parameters: {'alpha': 0.024893408377948, 'l1_ratio': 0.4350792012375208}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,306] Trial 26 finished with value: 0.31040872803593345 and parameters: {'alpha': 0.004555805905741285, 'l1_ratio': 0.5714290996710885}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,438] Trial 27 finished with value: 0.3093072968127273 and parameters: {'alpha': 0.0033746332286740837, 'l1_ratio': 0.4606094076384396}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,539] Trial 28 finished with value: 0.3309971630460645 and parameters: {'alpha': 0.1675060103222281, 'l1_ratio': 0.47004021325071355}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,634] Trial 29 finished with value: 0.3136882844581529 and parameters: {'alpha': 0.015641844531471102, 'l1_ratio': 0.5818511254540335}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,775] Trial 30 finished with value: 0.31920299440141503 and parameters: {'alpha': 0.037729988996860454, 'l1_ratio': 0.6829580149968447}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:37,961] Trial 31 finished with value: 0.3092280678189412 and parameters: {'alpha': 0.0033227896175570854, 'l1_ratio': 0.4117916518540398}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:38,091] Trial 32 finished with value: 0.3101564360846162 and parameters: {'alpha': 0.006195127737453192, 'l1_ratio': 0.3620794207412164}. Best is trial 23 with value: 0.3092004774177247.
[I 2026-04-15 06:28:38,225] Trial 33 finished with value: 0.30914657860532735 and parameters: {'alpha': 0.002697891356157296, 'l1_ratio': 0.4679805555278105}. Best is trial 33 with value: 0.30914657860532735.
[I 2026-04-15 06:28:38,436] Trial 34 finished with value: 0.3121156990897747 and parameters: {'alpha': 0.016681877766255543, 'l1_ratio': 0.38372205242140195}. Best is trial 33 with value: 0.30914657860532735.
[I 2026-04-15 06:28:38,595] Trial 35 finished with value: 0.3097554043887054 and parameters: {'alpha': 0.00034816800098729964, 'l1_ratio': 0.5091986488778314}. Best is trial 33 with value: 0.30914657860532735.
[I 2026-04-15 06:28:38,731] Trial 36 finished with value: 0.3118193240519724 and parameters: {'alpha': 0.009029629002792756, 'l1_ratio': 0.650741555772639}. Best is trial 33 with value: 0.30914657860532735.
[I 2026-04-15 06:28:38,904] Trial 37 finished with value: 0.3106776058046403 and parameters: {'alpha': 1.0348266779080482e-05, 'l1_ratio': 0.7479445266192206}. Best is trial 33 with value: 0.30914657860532735.
[I 2026-04-15 06:28:39,051] Trial 38 finished with value: 0.30912719573602065 and parameters: {'alpha': 0.0022609439867137984, 'l1_ratio': 0.5401041022052621}. Best is trial 38 with value: 0.30912719573602065.
[I 2026-04-15 06:28:39,190] Trial 39 finished with value: 0.3101879562523289 and parameters: {'alpha': 0.00016583870490669025, 'l1_ratio': 0.5350975750257193}. Best is trial 38 with value: 0.30912719573602065.
[I 2026-04-15 06:28:39,309] Trial 40 finished with value: 0.325177739426669 and parameters: {'alpha': 0.09212809057460414, 'l1_ratio': 0.6093917524676004}. Best is trial 38 with value: 0.30912719573602065.
[I 2026-04-15 06:28:39,442] Trial 41 finished with value: 0.30916099761894966 and parameters: {'alpha': 0.0023560885814053237, 'l1_ratio': 0.478180862164745}. Best is trial 38 with value: 0.30912719573602065.
[I 2026-04-15 06:28:39,581] Trial 42 finished with value: 0.3089992618628407 and parameters: {'alpha': 0.0018220540809302536, 'l1_ratio': 0.5047700395388509}. Best is trial 42 with value: 0.3089992618628407.
[I 2026-04-15 06:28:39,709] Trial 43 finished with value: 0.3090351005806383 and parameters: {'alpha': 0.0019813323340748877, 'l1_ratio': 0.5299041519042302}. Best is trial 42 with value: 0.3089992618628407.
[I 2026-04-15 06:28:39,840] Trial 44 finished with value: 0.309484803939155 and parameters: {'alpha': 0.00048599656685329313, 'l1_ratio': 0.5358142270686387}. Best is trial 42 with value: 0.3089992618628407.
[I 2026-04-15 06:28:40,015] Trial 45 finished with value: 0.31133734693430637 and parameters: {'alpha': 0.009538487155409534, 'l1_ratio': 0.4934781303688091}. Best is trial 42 with value: 0.3089992618628407.
[I 2026-04-15 06:28:40,211] Trial 46 finished with value: 0.31029496973319404 and parameters: {'alpha': 0.0001097411648936072, 'l1_ratio': 0.7377009680831095}. Best is trial 42 with value: 0.3089992618628407.
[I 2026-04-15 06:28:40,362] Trial 47 finished with value: 0.3090339170944173 and parameters: {'alpha': 0.0014704546330336593, 'l1_ratio': 0.6064364230313604}. Best is trial 42 with value: 0.3089992618628407.
[I 2026-04-15 06:28:40,530] Trial 48 finished with value: 0.3088858634400933 and parameters: {'alpha': 0.001557932637720389, 'l1_ratio': 0.8514086872665616}. Best is trial 48 with value: 0.3088858634400933.
[I 2026-04-15 06:28:40,667] Trial 49 finished with value: 0.3088190341437903 and parameters: {'alpha': 0.001457796619973083, 'l1_ratio': 0.8404299651354249}. Best is trial 49 with value: 0.3088190341437903.

In [14]:
print("Best Elastic Net root mean squared error:", study_elastic_net.best_value)
print("Best Elastic Net params:")
study_elastic_net.best_params

Best Elastic Net root mean squared error: 0.3088190341437903
Best Elastic Net params:

{'alpha': 0.001457796619973083, 'l1_ratio': 0.8404299651354249}

# Elastic Net Tuning Result

This output shows the best cross-validated RMSE found by Optuna for Elastic Net, along with the corresponding hyperparameters.

The next step is to repeat the same process for Ridge, Linear Regression,HistGradientBoosting and Random Forest and compare the tuned models.

In [15]:
def objective_ridge(trial):
    # Define hyperparameters to tune
    model = Ridge(
        alpha=trial.suggest_float("alpha", 1e-5, 1e2, log=True),
        solver=trial.suggest_categorical("solver", ['auto', 'svd', 'cholesky', 'lsqr', 'sag']),
    )

    model_pipeline = model

    cv_results = cross_validate(
        estimator=model_pipeline,
        X=X_train,
        y=y_train,
        cv=CV,
        scoring={"neg_root_mean_squared_error": "neg_root_mean_squared_error"},
        n_jobs=-1,
        return_train_score=False,
    )

    return -np.mean(cv_results["test_neg_root_mean_squared_error"])

# Ridge Objective Function

This function defines the search space for Ridge and evaluates each configuration using cross-validated RMSE.

It's worth noting that Ridge regression is a technique used to address overfitting by adding a penalty to the model's complexity.

In [16]:
study_ridge = optuna.create_study(direction="minimize")
study_ridge.optimize(objective_ridge, n_trials=50)

[I 2026-04-15 06:28:40,754] A new study created in memory with name: no-name-62da80b1-0ada-44c7-8b2a-267d186b7256
[I 2026-04-15 06:28:40,885] Trial 0 finished with value: 0.3106495986777894 and parameters: {'alpha': 0.03479154738357961, 'solver': 'svd'}. Best is trial 0 with value: 0.3106495986777894.
[I 2026-04-15 06:28:44,518] Trial 1 finished with value: 0.31269273657445046 and parameters: {'alpha': 0.0001623888724018204, 'solver': 'sag'}. Best is trial 0 with value: 0.3106495986777894.
[I 2026-04-15 06:28:44,648] Trial 2 finished with value: 0.3103643546980192 and parameters: {'alpha': 0.20680087223829108, 'solver': 'auto'}. Best is trial 2 with value: 0.3103643546980192.
[I 2026-04-15 06:28:44,732] Trial 3 finished with value: 0.30926224433083715 and parameters: {'alpha': 56.01699596591401, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:28:44,851] Trial 4 finished with value: 0.31103925085815637 and parameters: {'alpha': 0.07859273644455558, 'solver': 'lsqr'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:28:51,984] Trial 5 finished with value: 0.3126914819168781 and parameters: {'alpha': 0.01704773902728813, 'solver': 'sag'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:28:52,090] Trial 6 finished with value: 0.311045453591985 and parameters: {'alpha': 0.0027724364932979082, 'solver': 'lsqr'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:28:56,258] Trial 7 finished with value: 0.31270771340415837 and parameters: {'alpha': 5.68536496155753, 'solver': 'sag'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:00,610] Trial 8 finished with value: 0.31269476976160526 and parameters: {'alpha': 0.018609511630644244, 'solver': 'sag'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:00,742] Trial 9 finished with value: 0.3093397935448399 and parameters: {'alpha': 36.08194661553893, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:00,822] Trial 10 finished with value: 0.31072278485920846 and parameters: {'alpha': 1.0757635533334877e-05, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:00,924] Trial 11 finished with value: 0.30937049654166043 and parameters: {'alpha': 90.44229496099204, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,078] Trial 12 finished with value: 0.309396987763706 and parameters: {'alpha': 95.04786271659395, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,151] Trial 13 finished with value: 0.3097996959799187 and parameters: {'alpha': 2.154652245813063, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,285] Trial 14 finished with value: 0.3098260399016252 and parameters: {'alpha': 8.162988104477423, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,410] Trial 15 finished with value: 0.30990651710376327 and parameters: {'alpha': 0.8559065085011026, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,580] Trial 16 finished with value: 0.30947455411486785 and parameters: {'alpha': 24.875542329142164, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,763] Trial 17 finished with value: 0.310025027918977 and parameters: {'alpha': 0.580629464479732, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:01,909] Trial 18 finished with value: 0.3096615589746255 and parameters: {'alpha': 15.431314972198633, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:02,055] Trial 19 finished with value: 0.30981121334919565 and parameters: {'alpha': 2.676735451400318, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:02,207] Trial 20 finished with value: 0.31071900123442064 and parameters: {'alpha': 0.0017393283692573602, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:02,472] Trial 21 finished with value: 0.30940511910557733 and parameters: {'alpha': 96.40150901866959, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:02,713] Trial 22 finished with value: 0.3094224527085572 and parameters: {'alpha': 28.422001757131063, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:02,910] Trial 23 finished with value: 0.30926677980605577 and parameters: {'alpha': 63.17086282098349, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,162] Trial 24 finished with value: 0.3097992797998739 and parameters: {'alpha': 25.85717368160964, 'solver': 'lsqr'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,360] Trial 25 finished with value: 0.30979876256841343 and parameters: {'alpha': 2.0809572794673903, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,491] Trial 26 finished with value: 0.3098405119603976 and parameters: {'alpha': 7.233130671093279, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,572] Trial 27 finished with value: 0.30993739922776303 and parameters: {'alpha': 0.7660279769828452, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,654] Trial 28 finished with value: 0.30940928987173544 and parameters: {'alpha': 29.434467412782887, 'solver': 'auto'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,746] Trial 29 finished with value: 0.31040275763106956 and parameters: {'alpha': 0.1792067659794888, 'solver': 'svd'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,830] Trial 30 finished with value: 0.3098530906590586 and parameters: {'alpha': 5.828383133521588, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,911] Trial 31 finished with value: 0.30929750078485124 and parameters: {'alpha': 74.81340086432321, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:03,995] Trial 32 finished with value: 0.3092735485464881 and parameters: {'alpha': 48.371273701776495, 'solver': 'cholesky'}. Best is trial 3 with value: 0.30926224433083715.
[I 2026-04-15 06:29:04,079] Trial 33 finished with value: 0.309262098882533 and parameters: {'alpha': 57.424085345477266, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:04,157] Trial 34 finished with value: 0.30971275838825757 and parameters: {'alpha': 13.265042692295145, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:04,241] Trial 35 finished with value: 0.30983650146167807 and parameters: {'alpha': 3.6874200851424432, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:04,337] Trial 36 finished with value: 0.310722333317328 and parameters: {'alpha': 0.0002166688608225853, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:04,404] Trial 37 finished with value: 0.3095509490201451 and parameters: {'alpha': 39.150835411829135, 'solver': 'lsqr'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:08,108] Trial 38 finished with value: 0.3127260306077998 and parameters: {'alpha': 12.749385425298984, 'solver': 'sag'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:08,183] Trial 39 finished with value: 0.31071183555617976 and parameters: {'alpha': 0.0050328804509398575, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:08,238] Trial 40 finished with value: 0.3105945638710102 and parameters: {'alpha': 0.06299531263415278, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:08,285] Trial 41 finished with value: 0.30926888096565536 and parameters: {'alpha': 64.45539060628383, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:08,331] Trial 42 finished with value: 0.3092861290937421 and parameters: {'alpha': 44.739208928705196, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:08,384] Trial 43 finished with value: 0.3092684747809006 and parameters: {'alpha': 50.498211904579136, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:10,498] Trial 44 finished with value: 0.3127290516276612 and parameters: {'alpha': 13.909877864172445, 'solver': 'sag'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:10,555] Trial 45 finished with value: 0.3095123335827029 and parameters: {'alpha': 58.4179089450666, 'solver': 'lsqr'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:10,604] Trial 46 finished with value: 0.30985259820931066 and parameters: {'alpha': 4.9422211221632315, 'solver': 'auto'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:10,663] Trial 47 finished with value: 0.3095790145112889 and parameters: {'alpha': 19.18272968312625, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:10,717] Trial 48 finished with value: 0.3094217288941848 and parameters: {'alpha': 99.09523957691702, 'solver': 'cholesky'}. Best is trial 33 with value: 0.309262098882533.
[I 2026-04-15 06:29:10,793] Trial 49 finished with value: 0.3102350769282948 and parameters: {'alpha': 0.31513276592248785, 'solver': 'auto'}. Best is trial 33 with value: 0.309262098882533.

In [17]:
print("Best Ridge RMSE:", study_ridge.best_value)
print("Best Ridge params:")
study_ridge.best_params

Best Ridge RMSE: 0.309262098882533
Best Ridge params:

{'alpha': 57.424085345477266, 'solver': 'cholesky'}

# Ridge Tuning Result

This output shows the best cross-validated RMSE found by Optuna for Ridge, along with the corresponding hyperparameters.

In [18]:
def objective_hist_gradient_boosting(trial):
    # Define hyperparameters to tune
    model = HistGradientBoostingRegressor(
        learning_rate=trial.suggest_float("learning_rate", 0.005, 0.3, log=True),
        max_iter=trial.suggest_int("max_iter", 100, 700),
        max_leaf_nodes=trial.suggest_int("max_leaf_nodes", 10, 150),
        max_depth=trial.suggest_int("max_depth", 3, 18),
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 3, 75),
        l2_regularization=trial.suggest_float(
            "l2_regularization", 1e-6, 10.0, log=True
        ),
        random_state=RANDOM_STATE,
    )

    model_pipeline = model

    cv_results = cross_validate(
        estimator=model_pipeline,
        X=X_train,
        y=y_train,
        cv=CV,
        scoring={"neg_root_mean_squared_error": "neg_root_mean_squared_error"},
        n_jobs=-1,
        return_train_score=False,
    )

    return -np.mean(cv_results["test_neg_root_mean_squared_error"])

# HistGradientBoosting Objective Function

This function defines the search space for HistGradientBoosting and evaluates each configuration using cross-validated RMSE.

In [19]:
study_hist_gradient_boosting = optuna.create_study(direction="minimize")
study_hist_gradient_boosting.optimize(objective_hist_gradient_boosting, n_trials=50)

[I 2026-04-15 06:29:10,836] A new study created in memory with name: no-name-ff264090-b014-4e3c-823b-6fc4aa1f4a92
[I 2026-04-15 06:29:23,364] Trial 0 finished with value: 0.2901160595690141 and parameters: {'learning_rate': 0.008236270212736228, 'max_iter': 603, 'max_leaf_nodes': 92, 'max_depth': 13, 'min_samples_leaf': 13, 'l2_regularization': 0.0004258307645261862}. Best is trial 0 with value: 0.2901160595690141.
[I 2026-04-15 06:29:24,905] Trial 1 finished with value: 0.2911330086498417 and parameters: {'learning_rate': 0.09705051122217026, 'max_iter': 305, 'max_leaf_nodes': 25, 'max_depth': 6, 'min_samples_leaf': 60, 'l2_regularization': 0.00014006436725054106}. Best is trial 0 with value: 0.2901160595690141.
[I 2026-04-15 06:29:29,490] Trial 2 finished with value: 0.2921321408057324 and parameters: {'learning_rate': 0.02187093889106647, 'max_iter': 638, 'max_leaf_nodes': 87, 'max_depth': 7, 'min_samples_leaf': 19, 'l2_regularization': 1.417644227396859e-06}. Best is trial 0 with value: 0.2901160595690141.
[I 2026-04-15 06:29:30,442] Trial 3 finished with value: 0.28992630717212386 and parameters: {'learning_rate': 0.07782186862932637, 'max_iter': 178, 'max_leaf_nodes': 71, 'max_depth': 5, 'min_samples_leaf': 31, 'l2_regularization': 2.5121663911203384e-06}. Best is trial 3 with value: 0.28992630717212386.
[I 2026-04-15 06:29:33,327] Trial 4 finished with value: 0.3140524921702092 and parameters: {'learning_rate': 0.19845742124394303, 'max_iter': 485, 'max_leaf_nodes': 83, 'max_depth': 7, 'min_samples_leaf': 44, 'l2_regularization': 0.00018298465097736294}. Best is trial 3 with value: 0.28992630717212386.
[I 2026-04-15 06:29:36,431] Trial 5 finished with value: 0.2909946585286769 and parameters: {'learning_rate': 0.038481311492606696, 'max_iter': 558, 'max_leaf_nodes': 59, 'max_depth': 4, 'min_samples_leaf': 72, 'l2_regularization': 0.00013581882814786764}. Best is trial 3 with value: 0.28992630717212386.
[I 2026-04-15 06:29:42,733] Trial 6 finished with value: 0.2843573330026845 and parameters: {'learning_rate': 0.008783915192468418, 'max_iter': 508, 'max_leaf_nodes': 125, 'max_depth': 17, 'min_samples_leaf': 30, 'l2_regularization': 2.9035511573809922e-06}. Best is trial 6 with value: 0.2843573330026845.
[I 2026-04-15 06:29:44,553] Trial 7 finished with value: 0.2861267513801166 and parameters: {'learning_rate': 0.03781805930880584, 'max_iter': 187, 'max_leaf_nodes': 116, 'max_depth': 15, 'min_samples_leaf': 32, 'l2_regularization': 0.00029333189311323845}. Best is trial 6 with value: 0.2843573330026845.
[I 2026-04-15 06:29:46,790] Trial 8 finished with value: 0.2938535237858614 and parameters: {'learning_rate': 0.10694774075571914, 'max_iter': 128, 'max_leaf_nodes': 88, 'max_depth': 13, 'min_samples_leaf': 8, 'l2_regularization': 7.128179564271617e-06}. Best is trial 6 with value: 0.2843573330026845.
[I 2026-04-15 06:29:48,093] Trial 9 finished with value: 0.33992156226989445 and parameters: {'learning_rate': 0.0060240465360129536, 'max_iter': 162, 'max_leaf_nodes': 46, 'max_depth': 10, 'min_samples_leaf': 41, 'l2_regularization': 0.01244430082931555}. Best is trial 6 with value: 0.2843573330026845.
[I 2026-04-15 06:29:51,130] Trial 10 finished with value: 0.2818454224898216 and parameters: {'learning_rate': 0.013739265474617702, 'max_iter': 380, 'max_leaf_nodes': 145, 'max_depth': 18, 'min_samples_leaf': 55, 'l2_regularization': 2.5310386026084633}. Best is trial 10 with value: 0.2818454224898216.
[I 2026-04-15 06:29:54,927] Trial 11 finished with value: 0.2814656746275633 and parameters: {'learning_rate': 0.015181005551000628, 'max_iter': 377, 'max_leaf_nodes': 149, 'max_depth': 17, 'min_samples_leaf': 54, 'l2_regularization': 4.929164673964995}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:29:56,768] Trial 12 finished with value: 0.2819972963846524 and parameters: {'learning_rate': 0.01614369750788661, 'max_iter': 329, 'max_leaf_nodes': 144, 'max_depth': 18, 'min_samples_leaf': 55, 'l2_regularization': 9.522981612657306}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:29:59,124] Trial 13 finished with value: 0.2829811388984683 and parameters: {'learning_rate': 0.01788114159124709, 'max_iter': 421, 'max_leaf_nodes': 147, 'max_depth': 16, 'min_samples_leaf': 58, 'l2_regularization': 8.599353068022015}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:00,679] Trial 14 finished with value: 0.28313802651733116 and parameters: {'learning_rate': 0.011512932631255914, 'max_iter': 301, 'max_leaf_nodes': 119, 'max_depth': 18, 'min_samples_leaf': 73, 'l2_regularization': 0.33712233754736737}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:03,069] Trial 15 finished with value: 0.29566337863552655 and parameters: {'learning_rate': 0.00506366790828986, 'max_iter': 356, 'max_leaf_nodes': 135, 'max_depth': 14, 'min_samples_leaf': 49, 'l2_regularization': 0.37911855502219466}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:05,619] Trial 16 finished with value: 0.28599023432951787 and parameters: {'learning_rate': 0.025711841078031716, 'max_iter': 418, 'max_leaf_nodes': 108, 'max_depth': 11, 'min_samples_leaf': 65, 'l2_regularization': 0.5920125696852055}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:08,198] Trial 17 finished with value: 0.28697964312917407 and parameters: {'learning_rate': 0.05877025088954331, 'max_iter': 230, 'max_leaf_nodes': 149, 'max_depth': 10, 'min_samples_leaf': 51, 'l2_regularization': 0.046512292335204326}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:10,637] Trial 18 finished with value: 0.2828856233042424 and parameters: {'learning_rate': 0.013732099665336546, 'max_iter': 254, 'max_leaf_nodes': 102, 'max_depth': 16, 'min_samples_leaf': 65, 'l2_regularization': 1.653029085347486}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:13,462] Trial 19 finished with value: 0.28666809728229037 and parameters: {'learning_rate': 0.028347057342311893, 'max_iter': 390, 'max_leaf_nodes': 132, 'max_depth': 12, 'min_samples_leaf': 46, 'l2_regularization': 0.05480432462347162}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:17,433] Trial 20 finished with value: 0.31654817703683125 and parameters: {'learning_rate': 0.2878482137094212, 'max_iter': 477, 'max_leaf_nodes': 136, 'max_depth': 15, 'min_samples_leaf': 37, 'l2_regularization': 2.2431671117529626}. Best is trial 11 with value: 0.2814656746275633.
[I 2026-04-15 06:30:19,369] Trial 21 finished with value: 0.280811221123087 and parameters: {'learning_rate': 0.015085102687086571, 'max_iter': 340, 'max_leaf_nodes': 150, 'max_depth': 18, 'min_samples_leaf': 53, 'l2_regularization': 9.636193638315381}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:21,877] Trial 22 finished with value: 0.28254234018505864 and parameters: {'learning_rate': 0.010268821641477934, 'max_iter': 386, 'max_leaf_nodes': 149, 'max_depth': 18, 'min_samples_leaf': 64, 'l2_regularization': 2.0902968658744703}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:24,607] Trial 23 finished with value: 0.29448411684265113 and parameters: {'learning_rate': 0.007133112378130209, 'max_iter': 259, 'max_leaf_nodes': 129, 'max_depth': 16, 'min_samples_leaf': 53, 'l2_regularization': 0.10288939974851548}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:28,112] Trial 24 finished with value: 0.28287367719321455 and parameters: {'learning_rate': 0.013952832578729646, 'max_iter': 448, 'max_leaf_nodes': 106, 'max_depth': 17, 'min_samples_leaf': 59, 'l2_regularization': 0.004340251263494198}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:32,215] Trial 25 finished with value: 0.29017225551092823 and parameters: {'learning_rate': 0.023679892574958963, 'max_iter': 539, 'max_leaf_nodes': 138, 'max_depth': 18, 'min_samples_leaf': 40, 'l2_regularization': 4.585723211186103}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:36,974] Trial 26 finished with value: 0.2970752325747299 and parameters: {'learning_rate': 0.04996907574867325, 'max_iter': 690, 'max_leaf_nodes': 120, 'max_depth': 15, 'min_samples_leaf': 48, 'l2_regularization': 1.193216454346003}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:40,158] Trial 27 finished with value: 0.2829765659775063 and parameters: {'learning_rate': 0.017822164058025884, 'max_iter': 357, 'max_leaf_nodes': 14, 'max_depth': 17, 'min_samples_leaf': 68, 'l2_regularization': 0.13556404963823787}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:43,480] Trial 28 finished with value: 0.2836833202989954 and parameters: {'learning_rate': 0.03161668000568936, 'max_iter': 291, 'max_leaf_nodes': 140, 'max_depth': 14, 'min_samples_leaf': 55, 'l2_regularization': 0.0133718020583499}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:47,614] Trial 29 finished with value: 0.2844850450489308 and parameters: {'learning_rate': 0.008236684893193338, 'max_iter': 352, 'max_leaf_nodes': 97, 'max_depth': 9, 'min_samples_leaf': 21, 'l2_regularization': 0.0009311044262845809}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:50,057] Trial 30 finished with value: 0.2822399909919756 and parameters: {'learning_rate': 0.012009368621921222, 'max_iter': 449, 'max_leaf_nodes': 113, 'max_depth': 13, 'min_samples_leaf': 61, 'l2_regularization': 3.6377826814535}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:52,036] Trial 31 finished with value: 0.2814964878179764 and parameters: {'learning_rate': 0.01730907503463227, 'max_iter': 326, 'max_leaf_nodes': 141, 'max_depth': 18, 'min_samples_leaf': 54, 'l2_regularization': 4.753267486571758}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:55,309] Trial 32 finished with value: 0.2814083075882988 and parameters: {'learning_rate': 0.017999843167128618, 'max_iter': 330, 'max_leaf_nodes': 150, 'max_depth': 17, 'min_samples_leaf': 53, 'l2_regularization': 0.5088220777092151}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:30:58,998] Trial 33 finished with value: 0.28407199430409347 and parameters: {'learning_rate': 0.021623665671578404, 'max_iter': 302, 'max_leaf_nodes': 126, 'max_depth': 17, 'min_samples_leaf': 43, 'l2_regularization': 0.6754386301525659}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:01,150] Trial 34 finished with value: 0.2817826182695099 and parameters: {'learning_rate': 0.019445142281076383, 'max_iter': 267, 'max_leaf_nodes': 150, 'max_depth': 16, 'min_samples_leaf': 35, 'l2_regularization': 8.76740230441787}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:02,710] Trial 35 finished with value: 0.28765466296510134 and parameters: {'learning_rate': 0.010123895506121947, 'max_iter': 219, 'max_leaf_nodes': 140, 'max_depth': 17, 'min_samples_leaf': 50, 'l2_regularization': 0.321616522988854}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:04,482] Trial 36 finished with value: 0.2853643790377271 and parameters: {'learning_rate': 0.03307492237147105, 'max_iter': 325, 'max_leaf_nodes': 43, 'max_depth': 14, 'min_samples_leaf': 69, 'l2_regularization': 0.7937916090379413}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:06,583] Trial 37 finished with value: 0.2817897785740142 and parameters: {'learning_rate': 0.016318612371080853, 'max_iter': 344, 'max_leaf_nodes': 69, 'max_depth': 15, 'min_samples_leaf': 59, 'l2_regularization': 4.454459040036099}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:13,234] Trial 38 finished with value: 0.2962093868858079 and parameters: {'learning_rate': 0.05075559567441685, 'max_iter': 422, 'max_leaf_nodes': 125, 'max_depth': 16, 'min_samples_leaf': 27, 'l2_regularization': 0.12470623543562315}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:15,592] Trial 39 finished with value: 0.3030635039670554 and parameters: {'learning_rate': 0.007174210584536123, 'max_iter': 218, 'max_leaf_nodes': 132, 'max_depth': 8, 'min_samples_leaf': 45, 'l2_regularization': 5.066373272626248e-05}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:19,158] Trial 40 finished with value: 0.29823014465936076 and parameters: {'learning_rate': 0.11575304483152896, 'max_iter': 280, 'max_leaf_nodes': 76, 'max_depth': 6, 'min_samples_leaf': 3, 'l2_regularization': 1.3568481612670407}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:21,291] Trial 41 finished with value: 0.28177519881026497 and parameters: {'learning_rate': 0.021158540927107308, 'max_iter': 269, 'max_leaf_nodes': 149, 'max_depth': 16, 'min_samples_leaf': 38, 'l2_regularization': 4.257638589767069}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:24,745] Trial 42 finished with value: 0.28258251635321374 and parameters: {'learning_rate': 0.022139575396113196, 'max_iter': 315, 'max_leaf_nodes': 138, 'max_depth': 17, 'min_samples_leaf': 38, 'l2_regularization': 4.139401532131454}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:30,253] Trial 43 finished with value: 0.28145048865331657 and parameters: {'learning_rate': 0.01412472069149718, 'max_iter': 365, 'max_leaf_nodes': 141, 'max_depth': 18, 'min_samples_leaf': 27, 'l2_regularization': 9.860068269963781}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:35,441] Trial 44 finished with value: 0.2815409208385976 and parameters: {'learning_rate': 0.01498662765432527, 'max_iter': 373, 'max_leaf_nodes': 141, 'max_depth': 18, 'min_samples_leaf': 19, 'l2_regularization': 7.181710153631136}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:39,837] Trial 45 finished with value: 0.28484648080113095 and parameters: {'learning_rate': 0.00996997188285083, 'max_iter': 406, 'max_leaf_nodes': 121, 'max_depth': 18, 'min_samples_leaf': 26, 'l2_regularization': 1.1275352847401683}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:50,846] Trial 46 finished with value: 0.28312102379614756 and parameters: {'learning_rate': 0.01303455521162863, 'max_iter': 459, 'max_leaf_nodes': 144, 'max_depth': 17, 'min_samples_leaf': 12, 'l2_regularization': 9.910230582381278}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:54,337] Trial 47 finished with value: 0.2864087131238554 and parameters: {'learning_rate': 0.029430999026873874, 'max_iter': 518, 'max_leaf_nodes': 127, 'max_depth': 18, 'min_samples_leaf': 54, 'l2_regularization': 0.21963849384517448}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:31:56,355] Trial 48 finished with value: 0.2848163578868036 and parameters: {'learning_rate': 0.03711830373027142, 'max_iter': 328, 'max_leaf_nodes': 113, 'max_depth': 17, 'min_samples_leaf': 57, 'l2_regularization': 2.3011452502203675}. Best is trial 21 with value: 0.280811221123087.
[I 2026-04-15 06:32:01,014] Trial 49 finished with value: 0.2824458519498391 and parameters: {'learning_rate': 0.008855601576758815, 'max_iter': 584, 'max_leaf_nodes': 133, 'max_depth': 15, 'min_samples_leaf': 61, 'l2_regularization': 0.5906810548473392}. Best is trial 21 with value: 0.280811221123087.

In [20]:
print("Best HistGradientBoosting RMSE:", study_hist_gradient_boosting.best_value)
print("Best HistGradientBoosting params:")
study_hist_gradient_boosting.best_params

Best HistGradientBoosting RMSE: 0.280811221123087
Best HistGradientBoosting params:

{'learning_rate': 0.015085102687086571,
 'max_iter': 340,
 'max_leaf_nodes': 150,
 'max_depth': 18,
 'min_samples_leaf': 53,
 'l2_regularization': 9.636193638315381}

# HistGradientBoosting Tuning Result

This output shows the best cross-validated RMSE found by Optuna for HistGradientBoosting, along with the corresponding hyperparameters.

In [21]:
def objective_random_forest(trial):
    # Define hyperparameters to tune
    model = RandomForestRegressor(
        n_estimators=trial.suggest_int("n_estimators", 80, 600),
        max_depth=trial.suggest_int("max_depth", 3, 25),
        min_samples_split=trial.suggest_int("min_samples_split", 2, 25),
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 1, 12),
        max_features=trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model_pipeline = model

    cv_results = cross_validate(
        estimator=model_pipeline,
        X=X_train,
        y=y_train,
        cv=CV,
        scoring={"neg_root_mean_squared_error": "neg_root_mean_squared_error"},
        n_jobs=-1,
        return_train_score=False,
    )

    return -np.mean(cv_results["test_neg_root_mean_squared_error"])

# Random Forest Objective Function

This function defines the search space for Random Forest and evaluates each configuration using cross-validated RMSE.

In [22]:
study_random_forest = optuna.create_study(direction="minimize")
study_random_forest.optimize(objective_random_forest, n_trials=50)

[I 2026-04-15 06:32:01,053] A new study created in memory with name: no-name-e390a9e9-77f1-45a3-a835-c1850b287296
[I 2026-04-15 06:32:09,265] Trial 0 finished with value: 0.2809459893012515 and parameters: {'n_estimators': 356, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 0 with value: 0.2809459893012515.
[I 2026-04-15 06:32:14,497] Trial 1 finished with value: 0.27754019259788665 and parameters: {'n_estimators': 493, 'max_depth': 18, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 1 with value: 0.27754019259788665.
[I 2026-04-15 06:32:21,767] Trial 2 finished with value: 0.2800454632736352 and parameters: {'n_estimators': 207, 'max_depth': 12, 'min_samples_split': 16, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 1 with value: 0.27754019259788665.
[I 2026-04-15 06:32:23,362] Trial 3 finished with value: 0.2737444267942809 and parameters: {'n_estimators': 139, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:27,366] Trial 4 finished with value: 0.2764469670977244 and parameters: {'n_estimators': 376, 'max_depth': 18, 'min_samples_split': 22, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:32,265] Trial 5 finished with value: 0.28141622048728687 and parameters: {'n_estimators': 154, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': None}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:38,418] Trial 6 finished with value: 0.2742903542970098 and parameters: {'n_estimators': 441, 'max_depth': 20, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:49,956] Trial 7 finished with value: 0.2825638147491104 and parameters: {'n_estimators': 441, 'max_depth': 5, 'min_samples_split': 24, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:53,700] Trial 8 finished with value: 0.2751857893689184 and parameters: {'n_estimators': 325, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:56,961] Trial 9 finished with value: 0.28096737368862645 and parameters: {'n_estimators': 132, 'max_depth': 19, 'min_samples_split': 20, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 3 with value: 0.2737444267942809.
[I 2026-04-15 06:32:59,472] Trial 10 finished with value: 0.2728769784357045 and parameters: {'n_estimators': 229, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 10 with value: 0.2728769784357045.
[I 2026-04-15 06:33:03,425] Trial 11 finished with value: 0.2733786007888366 and parameters: {'n_estimators': 242, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 10 with value: 0.2728769784357045.
[I 2026-04-15 06:33:07,418] Trial 12 finished with value: 0.2739828211502714 and parameters: {'n_estimators': 260, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 10 with value: 0.2728769784357045.
[I 2026-04-15 06:33:10,248] Trial 13 finished with value: 0.27374468152632475 and parameters: {'n_estimators': 255, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 10 with value: 0.2728769784357045.
[I 2026-04-15 06:33:16,728] Trial 14 finished with value: 0.27250443978673683 and parameters: {'n_estimators': 593, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:24,947] Trial 15 finished with value: 0.27467077609322754 and parameters: {'n_estimators': 560, 'max_depth': 24, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:31,077] Trial 16 finished with value: 0.2732872976110701 and parameters: {'n_estimators': 552, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:41,058] Trial 17 finished with value: 0.2745852843044052 and parameters: {'n_estimators': 586, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:42,327] Trial 18 finished with value: 0.27457128623701493 and parameters: {'n_estimators': 87, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:45,824] Trial 19 finished with value: 0.27928764811229345 and parameters: {'n_estimators': 310, 'max_depth': 16, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:52,485] Trial 20 finished with value: 0.2747094473332107 and parameters: {'n_estimators': 399, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:33:59,024] Trial 21 finished with value: 0.27326106409382994 and parameters: {'n_estimators': 546, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:34:05,579] Trial 22 finished with value: 0.2732549656808965 and parameters: {'n_estimators': 507, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:34:12,276] Trial 23 finished with value: 0.2726479882913995 and parameters: {'n_estimators': 481, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 14 with value: 0.27250443978673683.
[I 2026-04-15 06:34:18,112] Trial 24 finished with value: 0.2714716412926129 and parameters: {'n_estimators': 490, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 24 with value: 0.2714716412926129.
[I 2026-04-15 06:34:26,776] Trial 25 finished with value: 0.2702021388351652 and parameters: {'n_estimators': 488, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:34:33,009] Trial 26 finished with value: 0.2945641236626037 and parameters: {'n_estimators': 596, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:34:41,788] Trial 27 finished with value: 0.27144353670456356 and parameters: {'n_estimators': 442, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:34:47,041] Trial 28 finished with value: 0.271312896114423 and parameters: {'n_estimators': 431, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:34:53,173] Trial 29 finished with value: 0.27129769264839465 and parameters: {'n_estimators': 430, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:34:58,684] Trial 30 finished with value: 0.28019259140041763 and parameters: {'n_estimators': 402, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:35:03,810] Trial 31 finished with value: 0.27133435204786116 and parameters: {'n_estimators': 443, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:35:11,065] Trial 32 finished with value: 0.27024552954889736 and parameters: {'n_estimators': 463, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 25 with value: 0.2702021388351652.
[I 2026-04-15 06:35:17,206] Trial 33 finished with value: 0.26980523320995187 and parameters: {'n_estimators': 513, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 33 with value: 0.26980523320995187.
[I 2026-04-15 06:35:22,744] Trial 34 finished with value: 0.2711085707019687 and parameters: {'n_estimators': 515, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 33 with value: 0.26980523320995187.
[I 2026-04-15 06:35:30,283] Trial 35 finished with value: 0.2711355087278762 and parameters: {'n_estimators': 511, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 33 with value: 0.26980523320995187.
[I 2026-04-15 06:35:35,952] Trial 36 finished with value: 0.2712287012857747 and parameters: {'n_estimators': 530, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 33 with value: 0.26980523320995187.
[I 2026-04-15 06:35:42,884] Trial 37 finished with value: 0.2751895151525042 and parameters: {'n_estimators': 467, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 33 with value: 0.26980523320995187.
[I 2026-04-15 06:35:46,590] Trial 38 finished with value: 0.2921603296491882 and parameters: {'n_estimators': 367, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 33 with value: 0.26980523320995187.
[I 2026-04-15 06:35:51,904] Trial 39 finished with value: 0.2697542403503709 and parameters: {'n_estimators': 467, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:06,514] Trial 40 finished with value: 0.2787846391303781 and parameters: {'n_estimators': 472, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:14,849] Trial 41 finished with value: 0.2714473650592018 and parameters: {'n_estimators': 525, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:19,194] Trial 42 finished with value: 0.27525626975640916 and parameters: {'n_estimators': 401, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:24,723] Trial 43 finished with value: 0.2702185619230026 and parameters: {'n_estimators': 464, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:32,767] Trial 44 finished with value: 0.27082361784554376 and parameters: {'n_estimators': 458, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:38,468] Trial 45 finished with value: 0.27616186762910966 and parameters: {'n_estimators': 489, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:36:56,095] Trial 46 finished with value: 0.27832912516028285 and parameters: {'n_estimators': 569, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:37:03,150] Trial 47 finished with value: 0.27985965355716297 and parameters: {'n_estimators': 415, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:37:06,999] Trial 48 finished with value: 0.2746404030180233 and parameters: {'n_estimators': 338, 'max_depth': 9, 'min_samples_split': 25, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 39 with value: 0.2697542403503709.
[I 2026-04-15 06:37:16,302] Trial 49 finished with value: 0.27870638038784357 and parameters: {'n_estimators': 309, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 39 with value: 0.2697542403503709.

In [23]:
print("Best Random Forest RMSE:", study_random_forest.best_value)
print("Best Random Forest params:")
study_random_forest.best_params

Best Random Forest RMSE: 0.2697542403503709
Best Random Forest params:

{'n_estimators': 467,
 'max_depth': 7,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt'}

# Random Forest Tuning Result

This output shows the best cross-validated RMSE found by Optuna for Random Forest, along with the corresponding hyperparameters.

At this point, all tuned candidate models can be compared directly to determine which one should move to final evaluation.

In [24]:
tuned_results_df = pd.DataFrame(
    [
        {
            "model": "ridge_tuned",
            "cv_RMSE_mean": -study_ridge.best_value,
        },
        {
            "model": "elastic_net_tuned",
            "cv_RMSE_mean": -study_elastic_net.best_value,
        },
        {
            "model": "hist_gradient_boosting_tuned",
            "cv_RMSE_mean": -study_hist_gradient_boosting.best_value,
        },
        {
            "model": "random_forest_tuned",
            "cv_RMSE_mean": -study_random_forest.best_value,
        },
    ]
).sort_values(by="cv_RMSE_mean", ascending=False).reset_index(drop=True)

tuned_results_df

                          model  cv_RMSE_mean
0           random_forest_tuned     -0.269754
1  hist_gradient_boosting_tuned     -0.280811
2             elastic_net_tuned     -0.308819
3                   ridge_tuned     -0.309262

# Tuned Model Comparison

This table compares the best tuned versions of the candidate models.

The model with the closest to zero cross-validated RMSE will be selected for final training and evaluation on the test set.

In [25]:
best_tuned_model_name = tuned_results_df.iloc[0]["model"]
best_tuned_model_name

'random_forest_tuned'

# Final Model Candidate

This cell identifies the best tuned model according to cross-validated RMSE.

This model will now be trained on the full training set and evaluated once on the untouched test set.

In [26]:
final_comparison_df = pd.concat(
    [
        all_results_df[["model", "cv_RMSE_mean"]],
        tuned_results_df.rename(columns={"cv_RMSE_mean": "cv_RMSE_mean"}),
    ],
    ignore_index=True,
).sort_values(by="cv_RMSE_mean", ascending=False).reset_index(drop=True)

final_comparison_df

                           model  cv_RMSE_mean
0            random_forest_tuned     -0.269754
1                  random_forest     -0.279589
2   hist_gradient_boosting_tuned     -0.280811
3         hist_gradient_boosting     -0.293833
4              elastic_net_tuned     -0.308819
5              linear_regression     -0.308941
6                    ridge_tuned     -0.309262
7                          ridge     -0.309869
8                    elastic_net     -0.373435
9                          lasso     -0.376444
10                 decision_tree     -0.391783
11                support_vector     -0.394451
12                         dummy     -0.534727

# Final Model Comparison

This table compares all evaluated models:

*  baseline models
*   candidate models
*   tuned models

The goal is to select the model with the best cross-validated RMSE, regardless of its complexity.

It is possible that a simpler model outperforms more complex ones, which would be preferable in terms of interpretability and robustness.

# Final Model Selection

The selected model is: random_forest_tuned

Justification:

*  Highest cross-validated RMSE
*  Stability across folds
*  Robustness and less overall overfitting

In [27]:
selected_model_name = final_comparison_df.iloc[0]["model"]
selected_model_name

'random_forest_tuned'

In [28]:
if selected_model_name == "dummy":
    final_estimator = DummyRegressor(strategy="mean")

elif selected_model_name == "linear_regression":
    final_estimator = LinearRegression(
        positive=True,
    )

elif selected_model_name == "decision_tree":
    final_estimator = DecisionTreeRegressor(
        random_state=RANDOM_STATE,
    )

elif selected_model_name == "random_forest":
    final_estimator = RandomForestRegressor(
        n_estimators=320,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

elif selected_model_name == "hist_gradient_boosting":
    final_estimator = HistGradientBoostingRegressor(
        random_state=RANDOM_STATE,
    )

elif selected_model_name == "random_forest_tuned":
    final_estimator = RandomForestRegressor(
        **study_random_forest.best_params,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

elif selected_model_name == "hist_gradient_boosting_tuned":
    final_estimator = HistGradientBoostingRegressor(
        **study_hist_gradient_boosting.best_params,
        random_state=RANDOM_STATE,
    )

elif selected_model_name == "support_vector":
    final_estimator = SVR(
    )

elif selected_model_name == "lasso":
    final_estimator = Lasso(
    )

elif selected_model_name == "elastic_net":
    final_estimator = ElasticNet(
    )

elif selected_model_name == "ridge":
    final_estimator = Ridge(
    )

elif selected_model_name == "ridge_tuned":
    final_estimator = Ridge(
        **study_ridge.best_params,
    )

elif selected_model_name == "linear_regression":
    final_estimator = LinearRegression(
        positive=True,
    )

elif selected_model_name == "elastic_net_tuned":
    final_estimator = ElasticNet(
        **study_elastic_net.best_params,
    )

else:
    raise ValueError(f"Unknown selected model: {selected_model_name}")

In [29]:
def make_model_pipeline(model):
    """
    Build a full modeling pipeline that combines preprocessing
    and classification in a single reproducible object.

    Parameters
    ----------
    preprocess_pipeline : sklearn transformer
        Preprocessing pipeline defined in Notebook 1.
    model : sklearn estimator
        Classification model.

    Returns
    -------
    sklearn.pipeline.Pipeline
        Full pipeline with preprocessing and model.
    """
    return Pipeline(
        steps=[
            ("model", model),
        ]
    )

In [30]:
final_model_pipeline = make_model_pipeline(
    model=final_estimator,
)

final_model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('model',
                 RandomForestRegressor(max_depth=7, max_features='sqrt',
                                       n_estimators=467, n_jobs=-1,
                                       random_state=42))])

# Final Training and Final Test Performance

This cell trains the selected model using the full training set.

At this point:

 *   all model selection decisions have already been made,
 *   hyperparameter tuning has already been completed if necessary,
 *   and the model is now ready for a single final evaluation on the test set.

In [31]:
y_pred = final_model_pipeline.predict(X_test)

if hasattr(final_model_pipeline, "predict_proba"):
    y_proba = final_model_pipeline.predict_proba(X_test)[:, 1]
else:
    y_proba = None

Now we can see what the model metrics (How the model performs) are using the test set.

In [32]:
test_results = {
    "MAE": mean_absolute_error(y_test, y_pred),
    "RMSE": root_mean_squared_error(y_test, y_pred),
    "MSE": mean_squared_error(y_test, y_pred),
    "r2_score": r2_score(y_test, y_pred),
    "huber_loss": huber_loss(y_test, y_pred),
}

if y_proba is not None:
    test_results["r2_score"] = r2_score(y_test, y_proba)

test_results_df = pd.DataFrame([test_results])
test_results_df

        MAE      RMSE       MSE  r2_score  huber_loss
0  0.172594  0.282891  0.080027  0.718412    0.040014

In [35]:
importances = final_estimator.feature_importances_
feature_importance_df = pd.DataFrame({'feature': X_train.columns, 'importance': importances})
feature_importance_df.sort_values('importance', ascending=False)

                  feature  importance
6             Log_TotalSF    0.167648
7           Log_GrLivArea    0.122300
0             OverallQual    0.100553
17              YearBuilt    0.088146
9               TotalBath    0.059161
1               ExterQual    0.046914
12             GarageCars    0.044203
3                BsmtQual    0.043851
8            Log_1stFlrSF    0.039125
4            GarageFinish    0.039053
13             GarageArea    0.033267
5             FireplaceQu    0.032003
18           YearRemodAdd    0.031984
2             KitchenQual    0.031145
11           AvgSFPerRoom    0.025921
14             Fireplaces    0.021628
10           TotRmsAbvGrd    0.020817
19       Foundation_PConc    0.016969
26      Neighborhood_Freq    0.013171
25               LotShape    0.004648
27  Functional_is_Special    0.003091
21      Foundation_CBlock    0.002746
23  GarageCond_is_Special    0.002384
20            MasVnr_None    0.002172
16              has_Alley    0.001929
24            SaleType_WD    0.001740
15              has_Fence    0.001689
22  GarageQual_is_Special    0.001478
28        Foundation_Slab    0.000262

Here we can see the selected model feature importance.

#Detailed Evaluation

All metrics used provide a more complete view of model behavior than a single metric.

In particular, they help in:

 *   Evaluating Regression Goodness-of-Fit,
 *   Evaluating weighted and unweighted error,
 *   Assign fair value to outliers.

# Final Conclusions

This notebook completed the first full modeling cycle of the Houses prices project.
Main outcomes

 *   A baseline performance level was established using simple models.
 *   Multiple regressors were compared under the same cross-validation setup.
 *   The strongest candidate models were tuned with Optuna.
 *   A final model was selected based on cross-validated RMSE.
 *   The selected model was evaluated on the test set.
  *  Error analysis and interpretation were performed.

Key methodological strengths

 *   The test set remained untouched until final evaluation.
 *   Model selection was based on quantitative evidence.
  *  Simpler models were not discarded unnecessarily.

Next steps

 *   refine feature engineering if needed,
 *   analyze subgroup failures more deeply,
  *  consider calibration or threshold adjustment,
  *  and prepare the model pipeline for deployment.